MKL compatibility
ssskkkky/EMME pull request #22
Opened 2024-06-01 10:54 UTC by ssskkkky

we can use emme in kylin2 now! where only MKL exists.

2024-06-01 23:50 UTC, 12ff54e requested changes
Looks good, except some minor format issues

2024-06-01 23:50 UTC, 12ff54e commented on include/solver.h
> +	#ifdef EMME_MKL
It seems like you formatter did not work properly here

2024-06-01 23:50 UTC, 12ff54e commented on include/solver.h
> +	#endif
Same format issue above

2024-06-02 05:19 UTC, ssskkkky commented
reformated

2024-06-02 05:21 UTC, 12ff54e approved these changes

2024-06-02 05:21 UTC, merged